### ISSUE TITLE
TFC Guidebook (patchouli) is empty

### ISSUE THREAD

**Issue by MaxLevs** [TerraFirmaGreg-Team/Modpack-1.20.x#377] opened 2024-06-01 05:15 UTC
### Version modpack Used

0.7.9

### Environment

singleplayer / server

### New Worlds

Yes

### Expected Behavior

Book is full of articles.

### Actual Behavior

Book is empty.
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/11697304/05c3d552-5ff9-4452-92db-a5f5a3457d15)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/11697304/901813f7-c303-4971-9359-d9ff40964960)

### Steps to Reproduce

1. Start the game
2. Enter a world (local or server)
3. Open an inventory
4. Click on the book icon

### Additional Information

Cannot check in official server 'cause of errors on connection.

**Comment by chemlzh** [comment] 2024-06-01 06:14
They have temporally banned, see 0.7.3 update changelog.

> The guide book from TFC is disabled, since the mod pack makes too many changes to the TFC and the book is not relevant, the relevant information will appear in the quests a little later.

**Comment by FriendlyCube** [comment] 2024-06-01 11:14
Patchouli book TFC:
https://terrafirmacraft.github.io/Field-Guide/en_us/ - инглиш
https://terrafirmacraft.github.io/Field-Guide/ru_ru/ - русский

**Comment by FriendlyCube** [comment] 2024-06-01 11:17
In the future, information from this book and the ae2 book will be in the quests

**Closed** 2024-06-01 16:55 UTC
Labels: 1. Type: Other Issue

**Comment by Nik-mmzd** [comment] 2024-06-01 19:24
The issue is **all multiblocks schematics** are unavailable in Field Guide Web:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/19509291/7d957578-3141-4366-b452-bff08e5a72ac)

Removing the Field Guide makes it impossible to create most multi-block structures, since the only visual source of their structure is the in-game Field Guide

**Comment by FriendlyCube** [comment] 2024-06-01 19:26
This is a problem. Until we rewrite the book into quests, we'll have to use a browser.

**Comment by Nik-mmzd** [comment] 2024-06-01 19:32
> we'll have to use a browser
...which is missing the most valuable information: multiblock structures schematics. Players literally are forced to **guess** how multiblock structures should be built.

**Also**, Field Guide Web **is also irrelevant** "since the mod pack makes too many changes to the TFC".
You're forcing players to use **irrelevant incomplete source** to... protect them from an irrelevant incomplete source!
I think Field Guide removal should be reverted as players looking for Field Guide will use **irrelevant** Field Guide Web.

**Comment by FriendlyCube** [comment] 2024-06-01 19:40
when we rewrite the book into quests, all the necessary information will be there. Players will also be able to write an issue about changing or adding information. I think this is a good solution to the problem

**Comment by Nik-mmzd** [comment] 2024-06-01 19:48
> **when** we rewrite the book into quests

...and until then players **have no way to view the multiblock schematics**, as the in-game Field Guide has been removed and the **web version of it doesn't have this information available**.

**Comment by MaxLevs** [comment] 2024-06-01 19:49
> when we rewrite the book into quests

Do you have a plan for this? Any tasks or epics? Or is this just in backlog?

**Comment by FriendlyCube** [comment] 2024-06-01 19:54
I was going to do the quests next week, but I can put it off for later.

> Do you have a plan for this?

**Comment by BabBimmaBome** [comment] 2024-06-01 20:10
> I was going to do the quests next week, but I can put it off for later.
> 
> > Do you have a plan for this?

:trollface:

**Comment by MaxLevs** [comment] 2024-06-02 05:06
> I was going to do the quests next week, but I can put it off for later.
> 
> > Do you have a plan for this?

So it's unplayable now. Take your time and good luck with project management.

**Comment by BabBimmaBome** [comment] 2024-06-02 05:08
Unplayable because bro can't read

**Comment by MaxLevs** [comment] 2024-06-02 05:44
@BabBimmaBome I don't quite understand your contribution to this conversation. @Nik-mmzd made a good point 'bout regression. 
In open source we all help each other on equal foot. Authors create their products to make the world better. And other people all over the world report bugs and contribute to figure out what needs to be done to make products better.
But all we have here is just a bunch of weird guys making fools of themselves and playing IT development lmfao. What kind of friking kindergarten is this? It's not "unplayable" because of your brother's reading skills. Y'all are simply devaluing this project with your own hands (with the tacit consent of all present contributors).
